REGION_CHOICES = [
    ("Amazonas", "Amazonas"),
    ("Áncash", "Áncash"),
    ("Apurímac", "Apurímac"),
    ("Arequipa", "Arequipa"),
    ("Ayacucho", "Ayacucho"),
    ("Cajamarca", "Cajamarca"),
    ("Callao", "Callao"),
    ("Cusco", "Cusco"),
    ("Huancavelica", "Huancavelica"),
    ("Huánuco", "Huánuco"),
    ("Ica", "Ica"),
    ("Junín", "Junín"),
    ("La Libertad", "La Libertad"),
    ("Lambayeque", "Lambayeque"),
    ("Lima", "Lima"),
    ("Loreto", "Loreto"),
    ("Madre de Dios", "Madre de Dios"),
    ("Moquegua", "Moquegua"),
    ("Pasco", "Pasco"),
    ("Piura", "Piura"),
    ("Puno", "Puno"),
    ("San Martín", "San Martín"),
    ("Tacna", "Tacna"),
    ("Tumbes", "Tumbes"),
    ("Ucayali", "Ucayali"),
]