# Generated by Django 5.2.7 on 2025-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0004_alter_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/users/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
