# Generated by Django 5.2.7 on 2025-10-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='_type',
            field=models.CharField(choices=[('accident', 'Accidente de tránsito'), ('theft', 'Robo o hurto'), ('assault', 'Agresión o violencia física'), ('domestic_violence', 'Violencia familiar o de pareja'), ('fraud', 'Estafa o fraude'), ('missing_person', 'Persona desaparecida'), ('vandalism', 'Vandalismo o daños a la propiedad'), ('drug_trafficking', 'Tráfico o consumo de drogas'), ('homicide', 'Homicidio o intento de homicidio'), ('harassment', 'Acoso o amenazas'), ('cybercrime', 'Delito informático'), ('sexual_abuse', 'Abuso o acoso sexual'), ('weapon_possession', 'Tenencia ilegal de armas'), ('public_disturbance', 'Alteración del orden público'), ('child_abuse', 'Maltrato infantil'), ('animal_abuse', 'Maltrato animal'), ('property_dispute', 'Conflicto por propiedad'), ('corruption', 'Corrupción o soborno'), ('kidnapping', 'Secuestro o tentativa'), ('other', 'Otro tipo de denuncia')], default='accident', max_length=50),
            preserve_default=False,
        ),
    ]
